# Generated by Django 4.2.5 on 2023-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptertopic',
            name='sort_order',
            field=models.IntegerField(blank=True, help_text='Якщо поле залишиться пустим, то після збереженні елемент буде виводитися останнім.', null=True, verbose_name='Порядок виводу'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва розділу'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва книги'),
        ),
        migrations.AlterField(
            model_name='textbookauthor',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Автор підручника'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва теми'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва відео'),
        ),
        migrations.AlterField(
            model_name='videoauthor',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва каналу, автора'),
        ),
    ]
