# Generated by Django 4.2.5 on 2023-10-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicvideo',
            options={'verbose_name': 'Тема-Відео', 'verbose_name_plural': '4. Тема-Відео'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Навчальне відео', 'verbose_name_plural': '3. Відеотека'},
        ),
        migrations.AddField(
            model_name='topic',
            name='sort_order_full_dec',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Розраховується автоматично', max_digits=6, null=True, verbose_name='Порядок виводу'),
        ),
    ]
