# Generated by Django 4.2.5 on 2023-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_topicvideo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='sort_order_full',
        ),
        migrations.AlterField(
            model_name='topic',
            name='sort_order_full_dec',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='Розраховується автоматично', max_digits=8, null=True, verbose_name='Порядок виводу dec'),
        ),
    ]
