# Generated by Django 4.2.5 on 2023-10-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_chaptertopic_sort_order_alter_chapter_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Назва тегу (українською)')),
                ('sort_order', models.IntegerField(blank=True, help_text='Якщо поле залишиться пустим, то після збереженні елемент буде виводитися останнім.', null=True, verbose_name='Порядок виводу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Виводити')),
                ('slug', models.SlugField(editable=False, help_text='заповнюється автоматично', max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Тег для відео',
                'verbose_name_plural': 'Теги для відео',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='school.tag', verbose_name='Теги'),
        ),
    ]
