# Generated by Django 4.2.5 on 2023-10-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_tag_video_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, help_text='заповнюється автоматично', max_length=255, unique=True, verbose_name='Тема-Відео')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.IntegerField(blank=True, help_text='Якщо поле залишиться пустим, то після збереженні елемент буде виводитися останнім.', null=True, verbose_name='Порядок виводу')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.topic', verbose_name='Тема')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.video', verbose_name='Відео')),
            ],
            options={
                'verbose_name': 'Тема-Відео',
                'verbose_name_plural': '4. Тема-Відео',
                'unique_together': {('topic', 'video')},
            },
        ),
    ]
