# Generated by Django 4.2.5 on 2023-10-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_topicvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicvideo',
            options={'verbose_name': 'Тема-Відео', 'verbose_name_plural': '5. Тема-Відео'},
        ),
        migrations.DeleteModel(
            name='ChapterTopic',
        ),
    ]
