# Generated by Django 4.2.5 on 2023-10-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_video_topic_alter_topic_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Заповніть це поле, якщо відео передбачено тільки для певного класу та предмету. Якщо відео можна використати для повторення в іншому класі, то вказувати Клас-Предмет не потрібно.', null=True, on_delete=django.db.models.deletion.PROTECT, to='school.gradesubject', verbose_name='Клас-Предмет'),
        ),
    ]
