# Generated by Django 4.2.5 on 2023-10-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_topic_sort_order_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='sort_order_main',
        ),
        migrations.AddField(
            model_name='topic',
            name='sort_order_full',
            field=models.IntegerField(blank=True, editable=False, help_text='Розраховується автоматично', null=True, verbose_name='Порядок виводу'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Номер розділу потрібен, щоб вивести розділи в правильному порядку', verbose_name='Номер розділу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Номер теми потрібен, щоб вивести теми в правильному порядку', verbose_name='Номер теми'),
            preserve_default=False,
        ),
    ]
