# Generated by Django 4.2.5 on 2023-10-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_topic_sort_order_main_topic_sort_order_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='html_code',
            field=models.TextField(blank=True, max_length=2000, verbose_name='HTML код для відео'),
        ),
    ]
