# Generated by Django 4.2.5 on 2023-10-15 08:59

from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_video_html_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='html_code',
            field=models.TextField(blank=True, max_length=2000, validators=[school.models.validate_html_code], verbose_name='HTML код відео з youtube'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, editable=False, help_text='Значення буде вибрано автоматично з попереднього поля при збереженні даних', max_length=255, unique=True, verbose_name='Посилання на відео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='text_book',
            field=models.ForeignKey(blank=True, help_text='Заповніть це поле, якщо в відео згадується певний підручник.', null=True, on_delete=django.db.models.deletion.PROTECT, to='school.textbook', verbose_name='Підручник'),
        ),
    ]
