# Generated by Django 4.2.5 on 2023-10-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_video_html_code_alter_video_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег для відео', 'verbose_name_plural': 'Довідник для відео: Теги для відео'},
        ),
        migrations.AlterModelOptions(
            name='textbook',
            options={'verbose_name': 'Підручник', 'verbose_name_plural': 'Довідник для підручників: Підручники'},
        ),
        migrations.AlterModelOptions(
            name='textbookauthor',
            options={'verbose_name': 'Автор підручника', 'verbose_name_plural': 'Довідник для підручників: Автори підручників'},
        ),
        migrations.AlterModelOptions(
            name='videoauthor',
            options={'verbose_name': 'Назва каналу, автора', 'verbose_name_plural': 'Довідник для відео: Канали, автори відео'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='science',
        ),
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва підручника'),
        ),
        migrations.AlterField(
            model_name='textbookauthor',
            name='title',
            field=models.CharField(help_text="Вкажіть ПІБ у вигляді ''Т.Тарасенко''", max_length=255, unique=True, verbose_name='Автор(и) підручника'),
        ),
    ]
