# Generated by Django 4.2.5 on 2023-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_tag_options_alter_textbook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Номер відео потрібен, щоб вивести відео в правильному порядку', verbose_name='Номер відео'),
        ),
    ]
