# Generated by Django 4.2.5 on 2023-10-16 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_video_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicvideo',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Опис до відео в рамках вибраної теми'),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Вкажіть оцінку від 0 до 12', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Оцінка відео'),
        ),
    ]
